{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "taroai.fullname" . }}-api
  labels:
    {{- include "taroai.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "taroai.fullname" . }}-api
    app.kubernetes.io/component: api
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- with .Values.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          - path: {{ default "/" .path }}
            pathType: {{ default "Prefix" .pathType }}
            backend:
              service:
                name: {{ include "taroai.fullname" $ }}-api
                port:
                  name: http
    {{- end }}
{{- end }}
